CREATE SCHEMA IF NOT EXISTS bank;

CREATE USER ccat WITH PASSWORD 'secret';
ALTER SCHEMA bank OWNER TO ccat;

REVOKE ALL ON SCHEMA public FROM public;
GRANT USAGE ON SCHEMA bank TO ccat;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA bank TO ccat;

ALTER DEFAULT PRIVILEGES IN SCHEMA bank
GRANT ALL ON TABLES TO ccat;

SET search_path TO bank, public;
