version: "3.9"

services:
  # Our postgres database
  db: # The service will be named db.
    image: postgres:14.15-alpine3.21
    restart: always # Always try to restart if this stops running.
    environment: # Provide environment variables. Format VAR: value.
      POSTGRES_USER: ${DB_USER}
      # POSTGRES_PASSWORD: feedthemsibsandpellots
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports: # Exposing ports for apps outside the docker-compose.
      - "${DB_PORT}:5432" # Format is hostPort:containerPort <=> outside:inside.
    volumes:
      - backend_masterclass:/var/lib/postgresql/data
    networks:
      - backend_masterclass_net

  # Adminer provides a nice web UI to connect to databases.
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula # Theme (https://github.com/vrana/adminer/tree/master/designs)
    ports: 
      - 3333:8080
    networks:
      - backend_masterclass_net

networks:
  backend_masterclass_net:

volumes:
  backend_masterclass:
