// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const blockSessionByID = `-- name: BlockSessionByID :exec
UPDATE sessions
SET is_blocked = true
WHERE id = $1
`

func (q *Queries) BlockSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, blockSessionByID, id)
	return err
}

const blockSessionByUsername = `-- name: BlockSessionByUsername :exec
UPDATE sessions
SET is_blocked = true
WHERE username = $1
`

func (q *Queries) BlockSessionByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, blockSessionByUsername, username)
	return err
}

const countBlockedSessions = `-- name: CountBlockedSessions :one
SELECT COUNT(*) FROM sessions
WHERE is_blocked = true
`

func (q *Queries) CountBlockedSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlockedSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM sessions
WHERE username = $1
`

func (q *Queries) CountSessions(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id,
  username,
  refresh_token,
  user_agent,
  client_ip,
  is_blocked,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, username, refresh_token, user_agent, client_ip, is_blocked, created_at, expires_at
`

type CreateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.Username,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteBlockedSessions = `-- name: DeleteBlockedSessions :exec
DELETE FROM sessions
WHERE is_blocked = true
`

func (q *Queries) DeleteBlockedSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteBlockedSessions)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByID = `-- name: DeleteSessionByID :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByID, id)
	return err
}

const deleteSessionByUsername = `-- name: DeleteSessionByUsername :exec
DELETE FROM sessions
WHERE username = $1
`

func (q *Queries) DeleteSessionByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByUsername, username)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, username, refresh_token, user_agent, client_ip, is_blocked, created_at, expires_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByUsername = `-- name: GetSessionByUsername :one
SELECT id, username, refresh_token, user_agent, client_ip, is_blocked, created_at, expires_at FROM sessions
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetSessionByUsername(ctx context.Context, username string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUsername, username)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listBlockedSessions = `-- name: ListBlockedSessions :many
SELECT id, username, refresh_token, user_agent, client_ip, is_blocked, created_at, expires_at FROM sessions
WHERE is_blocked = true
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListBlockedSessionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBlockedSessions(ctx context.Context, arg ListBlockedSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.RefreshToken,
			&i.UserAgent,
			&i.ClientIp,
			&i.IsBlocked,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, username, refresh_token, user_agent, client_ip, is_blocked, created_at, expires_at FROM sessions
WHERE username = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListSessionsParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.RefreshToken,
			&i.UserAgent,
			&i.ClientIp,
			&i.IsBlocked,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockSessionByID = `-- name: UnblockSessionByID :exec
UPDATE sessions
SET is_blocked = false
WHERE id = $1
`

func (q *Queries) UnblockSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unblockSessionByID, id)
	return err
}

const unblockSessionByUsername = `-- name: UnblockSessionByUsername :exec
UPDATE sessions
SET is_blocked = false
WHERE username = $1
`

func (q *Queries) UnblockSessionByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, unblockSessionByUsername, username)
	return err
}

const updateSessionByID = `-- name: UpdateSessionByID :one
UPDATE sessions
SET
  refresh_token = $2,
  user_agent = $3,
  client_ip = $4,
  is_blocked = $5,
  expires_at = $6
WHERE
  id = $1
RETURNING id, username, refresh_token, user_agent, client_ip, is_blocked, created_at, expires_at
`

type UpdateSessionByIDParams struct {
	ID           uuid.UUID `json:"id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) UpdateSessionByID(ctx context.Context, arg UpdateSessionByIDParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionByID,
		arg.ID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateSessionByUsername = `-- name: UpdateSessionByUsername :one
UPDATE sessions
SET
  refresh_token = $2,
  user_agent = $3,
  client_ip = $4,
  is_blocked = $5,
  expires_at = $6
WHERE
  username = $1
RETURNING id, username, refresh_token, user_agent, client_ip, is_blocked, created_at, expires_at
`

type UpdateSessionByUsernameParams struct {
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) UpdateSessionByUsername(ctx context.Context, arg UpdateSessionByUsernameParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, updateSessionByUsername,
		arg.Username,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
