package api

import (
	mockdb "backend-masterclass/db/mock"
	"backend-masterclass/db/sqlc"
	"backend-masterclass/token"
	u "backend-masterclass/util"
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	"go.uber.org/mock/gomock"
)

func randomAccount(owner string) sqlc.Account {

	return sqlc.Account{
		ID:       u.RandomInt(1, 100),
		Owner:    owner,
		Balance:  u.RandomMoney(),
		Currency: u.RandCurrency(),
	}
}

// We're using json.Unmarshal of a bytes.Buffer because we're using httptest.responseRecorder.Body which is a bytes.Buffer.
func requireBodyMatchAccount(t *testing.T,
	account sqlc.Account,
	body *bytes.Buffer,
) {
	data, err := io.ReadAll(body)
	require.NoError(t, err)

	var gotAccount sqlc.Account
	err = json.Unmarshal(data, &gotAccount)
	require.NoError(t, err)
	require.Equal(t, account, gotAccount)
}

func TestCreateAccountAPI(t *testing.T) {
	user, _ := randomUser()
	account := randomAccount(user.Username)
	account.Balance = 0

	testCases := []struct {
		name string
		// This is what's going to be put into the request body.
		body      sqlc.CreateAccountParams
		setupAuth func(
			t *testing.T,
			request *http.Request,
			tokenMaker token.Maker,
			authorizationType string,
			username string,
			duration time.Duration,
		)
		buildStubs    func(store *mockdb.MockStore)
		checkResponse func(t *testing.T, recorder *httptest.ResponseRecorder)
	}{
		{
			name: "ok",
			body: sqlc.CreateAccountParams{
				Owner:    account.Owner,
				Balance:  account.Balance,
				Currency: account.Currency,
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {

				// I expect the CreateAccount method to be called once with any context and params with the same owner and currency as the account.
				store.EXPECT().CreateAccount(gomock.Any(),
					gomock.Eq(sqlc.CreateAccountParams{
						Owner:    account.Owner,
						Balance:  0,
						Currency: account.Currency,
					})).
					Times(1).
					Return(account, nil)

			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {

				require.Equal(t, http.StatusOK, recorder.Code)
				requireBodyMatchAccount(t, account, recorder.Body)

			},
		},
		{
			// In this case we are simulating an internal error in the database. Since the query was generated by sqlc, we can be sure that the error is due to a problem in the database.
			name: "internal error",
			body: sqlc.CreateAccountParams{
				Owner:    account.Owner,
				Balance:  account.Balance,
				Currency: account.Currency,
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {
				arg := sqlc.CreateAccountParams{
					Owner:    account.Owner,
					Balance:  account.Balance,
					Currency: account.Currency,
				}

				store.EXPECT().CreateAccount(gomock.Any(), gomock.Eq(arg)).
					Times(1).
					Return(sqlc.Account{}, sqlc.ErrConnection)

				store.EXPECT().TranslateError(gomock.Any()).Times(1).
					Return(sqlc.ErrConnection)

			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {

				require.Equal(t, http.StatusInternalServerError, recorder.Code)
			},
		},
		{
			name: "bad request",
			body: sqlc.CreateAccountParams{
				Owner:    account.Owner,
				Balance:  account.Balance,
				Currency: "50",
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {

				// What this means is I expect the GetAccount method with any context and any account ID as the query id to be called 0 times.
				store.EXPECT().CreateAccount(gomock.Any(), gomock.Any()).
					Times(0)

			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {

				require.Equal(t, http.StatusBadRequest, recorder.Code)
			},
		},
	}

	for i := range testCases {
		tc := testCases[i]

		t.Run(tc.name, func(t *testing.T) {

			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			store := mockdb.NewMockStore(ctrl)
			tokenMaker, err := token.NewPasetoMaker(u.RandomStr(32))
			require.NoError(t, err)
			config := u.Config{
				AccessTokenDuration: time.Minute,
			}

			// build stubs.
			tc.buildStubs(store)

			// Starting test server and sending request.
			server := NewServer(store, config, tokenMaker)
			recorder := httptest.NewRecorder()

			// We create a json encoder from the reqBody buffer and marshal tc.body into it.
			reqBody := new(bytes.Buffer)
			err = json.NewEncoder(reqBody).Encode(tc.body)
			require.NoError(t, err)

			url := "/accounts"
			request, err := http.NewRequest(http.MethodPost, url, reqBody)
			require.NoError(t, err)

			tc.setupAuth(t, request, tokenMaker, authorisationTypeBearer, user.Username, config.AccessTokenDuration)

			// We use the inner ServeHTTP method and not Gin's Run method
			// because we want to use our recorder as a response writer.
			server.Router.ServeHTTP(recorder, request)
			tc.checkResponse(t, recorder)

		})
	}
}

func TestGetAccountAPI(t *testing.T) {
	user, _ := randomUser()
	account := randomAccount(user.Username)

	testCases := []struct {
		name      string
		accountId int64
		setupAuth func(
			t *testing.T,
			request *http.Request,
			tokenMaker token.Maker,
			authorizationType string,
			username string,
			duration time.Duration,
		)
		buildStubs    func(store *mockdb.MockStore)
		checkResponse func(t *testing.T, recorder *httptest.ResponseRecorder)
	}{
		{
			name:      "ok",
			accountId: account.ID,
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {

				store.EXPECT().GetAccount(gomock.Any(), gomock.Eq(account.ID)).
					Times(1).
					Return(account, nil)

			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {

				require.Equal(t, http.StatusOK, recorder.Code)
				requireBodyMatchAccount(t, account, recorder.Body)

			},
		},
		{
			name:      "not found",
			accountId: account.ID,
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {

				store.EXPECT().GetAccount(gomock.Any(), gomock.Eq(account.ID)).
					Times(1).
					Return(sqlc.Account{}, sqlc.ErrRecordNotFound)

				// TODO: Uncomment after translating error in server.GetAccount.
				// store.EXPECT().TranslateError(gomock.Any()).Times(1).
				// 	Return(sqlc.ErrRecordNotFound)
			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {

				require.Equal(t, http.StatusNotFound, recorder.Code)
			},
		},
		{
			// In this case we are simulating an internal error in the database. Since the query was generated by sqlc, we can be sure that the error is due to a problem in the database.
			name:      "internal error",
			accountId: account.ID,
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {

				store.EXPECT().GetAccount(gomock.Any(), gomock.Eq(account.ID)).
					Times(1).
					Return(sqlc.Account{}, sqlc.ErrConnection)

				// TODO: Uncomment after translating error in server.GetAccount.
				// store.EXPECT().TranslateError(gomock.Any()).Times(1).
				// 	Return(sqlc.ErrConnection)
			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {

				require.Equal(t, http.StatusInternalServerError, recorder.Code)
			},
		},
		{
			// In this case we are simulating a bad request. The account ID is invalid( should be >=1 ). The query should not be activated.
			name:      "bad request",
			accountId: -1,
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {

				// What this means is I expect the GetAccount method with any context and any account ID as the query id to be called 0 times.
				store.EXPECT().GetAccount(gomock.Any(), gomock.Any()).
					Times(0)

			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {

				require.Equal(t, http.StatusBadRequest, recorder.Code)
			},
		},
	}

	for i := range testCases {
		tc := testCases[i]

		t.Run(tc.name, func(t *testing.T) {

			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			store := mockdb.NewMockStore(ctrl)
			tokenMaker, err := token.NewPasetoMaker(u.RandomStr(32))
			config := u.Config{
				AccessTokenDuration: time.Minute,
			}
			require.NoError(t, err)

			// build stubs.
			tc.buildStubs(store)

			// Starting test server and sending request.
			server := NewServer(store, config, tokenMaker)
			recorder := httptest.NewRecorder()

			url := fmt.Sprintf("/accounts/%d", tc.accountId)
			request, err := http.NewRequest(http.MethodGet, url, nil)
			require.NoError(t, err)

			tc.setupAuth(t, request, tokenMaker, authorisationTypeBearer, user.Username, config.AccessTokenDuration)

			// We use the inner ServeHTTP method and not Gin's Run method
			// because we want to use our recorder as a response writer.
			server.Router.ServeHTTP(recorder, request)
			tc.checkResponse(t, recorder)

		})
	}
}

func TestListAccountsAPI(t *testing.T) {
	user, _ := randomUser()

	n := 5
	accounts := make([]sqlc.Account, n)
	for i := 0; i < n; i++ {
		accounts[i] = randomAccount(user.Username)
	}

	// URL query parameters.
	type Query struct {
		pageID   int
		pageSize int
	}

	testCases := []struct {
		name      string
		query     Query
		setupAuth func(
			t *testing.T,
			request *http.Request,
			tokenMaker token.Maker,
			authorizationType string,
			username string,
			duration time.Duration,
		)
		buildStubs    func(store *mockdb.MockStore)
		checkResponse func(t *testing.T, recorder *httptest.ResponseRecorder)
	}{
		{
			name: "ok",
			query: Query{
				pageID:   1,
				pageSize: n,
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorizationType, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {
				args := sqlc.ListAccountsParams{
					Owner:  user.Username,
					Limit:  int32(n),
					Offset: 0,
				}

				store.EXPECT().
					ListAccounts(gomock.Any(), gomock.Eq(args)).
					Times(1).
					Return(accounts, nil)
			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {
				require.Equal(t, http.StatusOK, recorder.Code)
			},
		},
		{
			name: "no authorisation",
			query: Query{
				pageID:   1,
				pageSize: n,
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				// We don't provide an authorization header.
			},
			buildStubs: func(store *mockdb.MockStore) {
				// This is supposed to fail at the server level.
				store.EXPECT().
					ListAccounts(gomock.Any(), gomock.Any()).
					Times(0)
			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {
				require.Equal(t, http.StatusUnauthorized, recorder.Code)
			},
		},
		{
			name: "internal error",
			query: Query{
				pageID:   1,
				pageSize: n,
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorisationTypeBearer, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {
				// This is supposed to fail at the db level.
				store.EXPECT().
					ListAccounts(gomock.Any(), gomock.Any()).
					Times(1).
					Return([]sqlc.Account{}, sqlc.ErrConnection)

				// TODO: Uncomment after translating error in server.GetAccount.
				// store.EXPECT().TranslateError(gomock.Any()).Times(1).
				// 	Return(sqlc.ErrConnection)
			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {
				require.Equal(t, http.StatusInternalServerError, recorder.Code)
			},
		},
		{
			name: "invalid page id",
			query: Query{
				pageID:   -1,
				pageSize: n,
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorisationTypeBearer, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {
				// This is supposed to fail at the server level.
				store.EXPECT().
					ListAccounts(gomock.Any(), gomock.Any()).
					Times(0)
			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {
				require.Equal(t, http.StatusBadRequest, recorder.Code)
			},
		},
		{
			name: "invalid page size",
			query: Query{
				pageID:   1,
				pageSize: 100000000,
			},
			setupAuth: func(
				t *testing.T,
				request *http.Request,
				tokenMaker token.Maker,
				authorizationType string,
				username string,
				duration time.Duration,
			) {
				addAuthorisation(t, request, tokenMaker, authorisationTypeBearer, user.Username, duration)
			},
			buildStubs: func(store *mockdb.MockStore) {
				// This is supposed to fail at the server level.
				store.EXPECT().
					ListAccounts(gomock.Any(), gomock.Any()).
					Times(0)
			},
			checkResponse: func(t *testing.T, recorder *httptest.ResponseRecorder) {
				require.Equal(t, http.StatusBadRequest, recorder.Code)
			},
		},
	}

	for i := range testCases {
		tc := testCases[i]

		t.Run(tc.name, func(t *testing.T) {

			// ------------Setting up main engine resources-------------------
			ctrl := gomock.NewController(t)
			defer ctrl.Finish()

			store := mockdb.NewMockStore(ctrl)

			// -----------Loading stubs with expected behaviour---------------
			tc.buildStubs(store)

			// ----------------Setting up fake routing------------------------
			server := newTestServer(t, store)
			recorder := httptest.NewRecorder()

			// ----------Setting up fake request & response writer------------
			url := "/accounts"
			request, err := http.NewRequest(http.MethodGet, url, nil)
			require.NoError(t, err)

			// ----------Putting authentication token in request--------------
			tc.setupAuth(t, request, server.TokenMaker, authorisationTypeBearer, user.Username, server.Config.AccessTokenDuration)

			// ---------Loading query parameters into the request-------------
			query := request.URL.Query()
			query.Add("page_id", fmt.Sprintf("%d", tc.query.pageID))
			query.Add("page_size", fmt.Sprintf("%d", tc.query.pageSize))
			request.URL.RawQuery = query.Encode()

			// ------------------Running the test------------------------------
			// We use the inner ServeHTTP method and not Gin's Run method
			// because we want to use our recorder as a response writer.
			server.Router.ServeHTTP(recorder, request)
			tc.checkResponse(t, recorder)
		})
	}
}
